# Config file for DeepForest pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 12
gpus: 2
distributed_backend: cuda
batch_size: 8

#Non-max supression of overlapping predictions
nms_thresh: 0.05
score_thresh: 0.3

train:

    csv_file:
    root_dir:
    
    #Optomizer  initial learning rate
    lr: 0.001

    #Print loss every n epochs
    epochs: 62
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False

    #pin images to GPU memory for fast training. This depends on GPU size and number of images.
    preload_images: True
    
validation:
    #callback args
    csv_file: 
    root_dir:
    #Intersection over union evaluation
    iou_threshold: 0.4
    val_accuracy_interval: 1
